services:
  t-learning-frontend:
    build:
      context: .
      secrets:
        - frontend_env
    container_name: t-learning-frontend
    restart: unless-stopped
    environment:
      PORT: ${PORT:-3001}
    ports:
      - "${PORT:-3001}:${PORT:-3001}"

secrets:
  frontend_env:
    file: ./.env
