const required = [
    "HOST",
    "PORT",
    "NODE_ENV",
    "APP_URL",
    "CORS_ORIGIN",
    "DB_USER",
    "DB_PASSWORD",
    "DB_NAME",
    "DB_PORT",
    "DB_URL",
    "RESEND_API_KEY",
    "RESEND_EMAIL_ADDRESS",
    "JWT_SECRET",
    "BETTER_AUTH_SECRET",
    "BETTER_AUTH_URL",
    "SESSION_EXPIRATION_DAYS",
    "SESSION_UPDATE_DAYS",
    "PASSWORD_MIN_LENGTH",
    "GOOGLE_CLIENT_ID",
    "GOOGLE_CLIENT_SECRET",
    "MINIO_ROOT_USER",
    "MINIO_ROOT_PASSWORD",
    "MINIO_ENDPOINT",
    "MINIO_PUBLIC_URL",
    "MINIO_PORT",
    "MINIO_CONSOLE_PORT",
    "MINIO_BUCKET",
    "MINIO_FORCE_PATH_STYLE",
    "MINIO_PRESIGNED_EXPIRY",
] as const;

for (const key of required) {
    if (!process.env[key]) {
        throw new Error(`Missing environment variable: ${key}`);
    }
}

export const env = {
    host: process.env.HOST!,
    port: process.env.PORT!,
    nodeEnv: process.env.NODE_ENV!,
    appUrl: process.env.APP_URL!,
    corsOrigin: process.env.CORS_ORIGIN!,
    dbUser: process.env.DB_USER!,
    dbPassword: process.env.DB_PASSWORD!,
    dbName: process.env.DB_NAME!,
    dbPort: process.env.DB_PORT!,
    dbUrl: process.env.DB_URL!,
    resendApiKey: process.env.RESEND_API_KEY!,
    resendEmailAddress: process.env.RESEND_EMAIL_ADDRESS!,
    jwtSecret: process.env.JWT_SECRET!,
    betterAuthSecret: process.env.BETTER_AUTH_SECRET!,
    betterAuthUrl: process.env.BETTER_AUTH_URL!,
    sessionExpirationDays: process.env.SESSION_EXPIRATION_DAYS!,
    sessionUpdateDays: process.env.SESSION_UPDATE_DAYS!,
    passwordMinLength: process.env.PASSWORD_MIN_LENGTH!,
    googleClientId: process.env.GOOGLE_CLIENT_ID!,
    googleClientSecret: process.env.GOOGLE_CLIENT_SECRET!,
    minioRootUser: process.env.MINIO_ROOT_USER!,
    minioRootPassword: process.env.MINIO_ROOT_PASSWORD!,
    minioEndpoint: process.env.MINIO_ENDPOINT!,
    minioPublicUrl: process.env.MINIO_PUBLIC_URL!,
    minioPort: process.env.MINIO_PORT!,
    minioConsolePort: process.env.MINIO_CONSOLE_PORT!,
    minioBucket: process.env.MINIO_BUCKET!,
    minioForcePathStyle: process.env.MINIO_FORCE_PATH_STYLE!,
    minioPresignedExpiry: process.env.MINIO_PRESIGNED_EXPIRY!,
}